### ISSUE TITLE
Gear VR

### ISSUE THREAD

**Issue by Hettylool** [NOLOVR/NOLO-Unity-SDK#2]
1.Because NOLO CV1 requires OTG function,Currently only supports 4 generations Gear VR.

2.Not support SamSung S6.

3.Before plug in NOLO CV1,You should  plug phone in the Gear VR first,make sure the oculus home is running.

**Comment by patstarace** [comment]
Hettylool,

Thanks for the tip...

"3.Before plug in NOLO CV1,You should plug phone in the Gear VR first,make sure the oculus home is running."

I want to try this, but how do we start the unity game from Oculus home?

Thank you

**Comment by demonixis** [comment]
I use NoloVR with my Samsung Galaxy S6, why did you say it's not working? The first GearVR (the white one) doesn't have an OTG port, so basically all mobiles using the first GearVR can't use Nolo. However, the new GearVR support all highend Samsung phone (including the S6) and have an OTG port.

@patstarace you can't have Oculus Home started because it runs only when you put the phone into the headset. For developers you just have to launch your compiled game from the menu then put the phone in the GearVR. Oculus Home is not required because it's started automaticaly.

**Comment by Hettylool** [comment]
@demonixis 

i have only a Samsung Galaxy S6, it is not working with it,so i say "Not support SamSung S6". maybe i have a bad Samsung Galaxy S6.

**Comment by demonixis** [comment]
It's very strange, what GearVR do you use? The black one? The white one doesn't have OTG support

**Comment by Hettylool** [comment]
@demonixis 
hi，what's your android version with your Samsung Galaxy S6.
Maybe android 6.0 don't support ,but android7.0 is okey,i want to figure out it.
